# Generated by Django 5.1.6 on 2025-06-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_comment_name_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
